import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import 'schema_versions.dart';

part 'app_database.g.dart'; // generated by `dart run build_runner build`

/// Durable offline store (Drift/SQLite). Survives process death so captured
/// attendance and its sync queue are never lost (Guideline §9, NFR-04).

/// Queued unit of work awaiting upload/sync.
class SyncTasks extends Table {
  TextColumn get id => text()(); // client idempotency key (UUID)
  TextColumn get type => text()(); // 'attendance' | 'import_commit' | ...
  TextColumn get payloadJson => text()();
  TextColumn get status => text().withDefault(const Constant('pendingSync'))();
  IntColumn get retryCount => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get lastAttemptAt => dateTime().nullable()();
  TextColumn get lastError => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Locally captured attendance evidence. [encryptedMediaPath] points at the
/// on-device AES-encrypted file; the raw key lives in secure storage.
class AttendanceDrafts extends Table {
  TextColumn get id => text()(); // == SyncTask.id (idempotency)
  TextColumn get sessionId => text()();
  TextColumn get carpenterId => text()();
  TextColumn get encryptedMediaPath => text()();
  TextColumn get qualityJson => text().nullable()(); // face/blur/light hints
  DateTimeColumn get capturedAt => dateTime()();
  TextColumn get capturedBy => text()();

  /// The consent notice shown before this capture (T-0.5.2).
  ///
  /// Nullable because rows queued by a pre-P0.5 build have no consent to
  /// backfill — inventing values would be worse than recording their absence.
  /// Presence is enforced at the write site in `capture_controller`, which is
  /// where the requirement actually belongs.
  IntColumn get consentVersion => integer().nullable()();
  TextColumn get consentLanguage => text().nullable()();
  DateTimeColumn get consentShownAt => dateTime().nullable()();
  TextColumn get consentContentHash => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Cached read-only reference lists (registered carpenters for a session) so
/// field search works offline. Never an authoritative master — display
/// freshness and direct corrections to Sales Eco (§8.6).
class CachedReferences extends Table {
  TextColumn get key => text()(); // e.g. 'session:<id>:registrations'
  TextColumn get valueJson => text()();
  DateTimeColumn get fetchedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {key};
}

/// Durable buffer for client audit events (Guideline §12, PRD FR-015). The
/// server is the authoritative store; this table exists so an event survives
/// process death on its way there.
///
/// The row class is named `AuditEventRow` because the domain-level `AuditEvent`
/// in `lib/core/audit/audit.dart` is what callers construct; this is only its
/// persisted shape.
@DataClassName('AuditEventRow')
class AuditEvents extends Table {
  /// Autoincrement so flush order is genuinely FIFO. [id] is a UUID and
  /// [occurredAt] can tie at millisecond resolution, so neither gives a stable
  /// ordering on its own.
  IntColumn get seq => integer().autoIncrement()();

  /// Client-generated UUID, so the server can dedupe a replayed batch.
  TextColumn get id => text().unique()();

  TextColumn get action => text()(); // AuditAction.name
  TextColumn get entity => text()();
  TextColumn get entityId => text()();
  TextColumn get correlationId => text()();

  /// Captured at emit time, never inferred at flush time. Field devices are
  /// shared: an event captured offline by one user can flush after a different
  /// user has logged in, and attributing it to whoever happens to be holding
  /// the phone would corrupt the audit trail.
  TextColumn get actorId => text()();

  TextColumn get remarks => text().nullable()();

  /// Client clock. The server should treat this as untrusted and pair it with
  /// its own receipt time.
  DateTimeColumn get occurredAt => dateTime()();

  IntColumn get attempts => integer().withDefault(const Constant(0))();
  TextColumn get lastError => text().nullable()();
}

/// Durable cache of fetched consent-notice versions (Guideline §10.3).
///
/// Keyed on `(version, language)` because the same version exists once per
/// language, and both must be able to coexist.
///
/// THIS TABLE DELIBERATELY NEVER PRUNES. Three reasons, recorded so the next
/// person does not "clean it up":
/// 1. `driftNoticeWriter` inserts with `InsertMode.insertOrReplace` against the
///    `(version, language)` primary key, so there is at most one row per
///    version per language. Growth is bounded by the number of notice versions
///    ever published — a handful over the app's lifetime, not unbounded.
/// 2. `NoticeRepository.resolve` picks the winner with a strict-`>` max fold,
///    not a sort, so how many rows the cache holds no longer influences which
///    notice wins. The regime that made pruning look urgent does not exist.
/// 3. Old versions are evidence. An `attendance_draft` stores the hash of the
///    version shown at capture time, and keeping that version's row is what
///    lets the wording be verified LOCALLY during a dispute. Pruning could
///    delete the very text the stored hash exists to check.
@DataClassName('ConsentNoticeRow')
class ConsentNotices extends Table {
  IntColumn get version => integer()();
  TextColumn get language => text()();
  TextColumn get title => text()();
  TextColumn get body => text()();

  /// The hash of this exact text, so a consent record can be verified against
  /// the version it names.
  ///
  /// Written but never read by production code, on purpose: `ConsentNotice` has
  /// no `contentHash` field, only `hash()`, so `driftNoticeReader` reconstructs
  /// notices without it. This column is the dispute-verification artifact —
  /// it is what makes a stored `attendance_drafts.consentContentHash`
  /// checkable offline. Do not delete it as dead weight.
  TextColumn get contentHash => text()();

  DateTimeColumn get fetchedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {version, language};
}

@DriftDatabase(
  tables: [
    SyncTasks,
    AttendanceDrafts,
    CachedReferences,
    AuditEvents,
    ConsentNotices,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.executor);

  /// Opens the on-device database across native and web (wasm). Tests use the
  /// primary constructor with an in-memory `NativeDatabase.memory()` executor.
  ///
  /// Both seams default to null, which is exactly today's production behaviour:
  /// drift_flutter then resolves `getApplicationDocumentsDirectory()` and
  /// `getTemporaryDirectory()` from `package:path_provider`. They exist so a
  /// TEST can exercise this real code path — `open()` plus the whole migration
  /// chain — against a temp directory, because neither path_provider call has a
  /// plugin implementation under `flutter_test`.
  ///
  /// `tempDirectoryPath` is not optional-in-practice for tests: drift_flutter
  /// defaults it to `getTemporaryDirectory()`, and that is the call that
  /// actually throws MissingPluginException, so seaming only the database
  /// directory would leave the test broken.
  AppDatabase.open({
    Future<Object> Function()? databaseDirectory,
    Future<String?> Function()? tempDirectoryPath,
  }) : super(
         driftDatabase(
           name: 'acsl_campaign',
           native: DriftNativeOptions(
             databaseDirectory: databaseDirectory,
             tempDirectoryPath: tempDirectoryPath,
           ),
           web: DriftWebOptions(
             // Relative URIs: both files are served from the web root because
             // they live in `web/`. Without this parameter drift_flutter's web
             // opener throws ArgumentError synchronously, which is why the web
             // build could not start.
             sqlite3Wasm: Uri.parse('sqlite3.wasm'),
             driftWorker: Uri.parse('drift_worker.js'),
           ),
         ),
       );

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onUpgrade: stepByStep(
      // v2 adds the audit buffer. The three v1 tables are untouched, which is
      // what makes the data-survival assertion in migration_test.dart hold.
      from1To2: (m, schema) async => m.createTable(schema.auditEvents),
      // v3 adds the consent cache and four NULLABLE columns on
      // attendance_drafts. Nothing is dropped, renamed or backfilled, which is
      // what makes the data-survival assertion in migration_test.dart hold:
      // a queued capture on a real device is field evidence nobody can retake.
      from2To3: (m, schema) async {
        await m.createTable(schema.consentNotices);
        await m.addColumn(
          schema.attendanceDrafts,
          schema.attendanceDrafts.consentVersion,
        );
        await m.addColumn(
          schema.attendanceDrafts,
          schema.attendanceDrafts.consentLanguage,
        );
        await m.addColumn(
          schema.attendanceDrafts,
          schema.attendanceDrafts.consentShownAt,
        );
        await m.addColumn(
          schema.attendanceDrafts,
          schema.attendanceDrafts.consentContentHash,
        );
      },
    ),
  );
}
