import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

part 'app_database.g.dart'; // generated by `dart run build_runner build`

/// Durable offline store (Drift/SQLite). Survives process death so captured
/// attendance and its sync queue are never lost (Guideline §9, NFR-04).

/// Queued unit of work awaiting upload/sync.
class SyncTasks extends Table {
  TextColumn get id => text()(); // client idempotency key (UUID)
  TextColumn get type => text()(); // 'attendance' | 'import_commit' | ...
  TextColumn get payloadJson => text()();
  TextColumn get status => text().withDefault(const Constant('pendingSync'))();
  IntColumn get retryCount => integer().withDefault(const Constant(0))();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get lastAttemptAt => dateTime().nullable()();
  TextColumn get lastError => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Locally captured attendance evidence. [encryptedMediaPath] points at the
/// on-device AES-encrypted file; the raw key lives in secure storage.
class AttendanceDrafts extends Table {
  TextColumn get id => text()(); // == SyncTask.id (idempotency)
  TextColumn get sessionId => text()();
  TextColumn get carpenterId => text()();
  TextColumn get encryptedMediaPath => text()();
  TextColumn get qualityJson => text().nullable()(); // face/blur/light hints
  DateTimeColumn get capturedAt => dateTime()();
  TextColumn get capturedBy => text()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Cached read-only reference lists (registered carpenters for a session) so
/// field search works offline. Never an authoritative master — display
/// freshness and direct corrections to Sales Eco (§8.6).
class CachedReferences extends Table {
  TextColumn get key => text()(); // e.g. 'session:<id>:registrations'
  TextColumn get valueJson => text()();
  DateTimeColumn get fetchedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {key};
}

@DriftDatabase(tables: [SyncTasks, AttendanceDrafts, CachedReferences])
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.executor);

  /// Opens the on-device database across native and web (wasm). Tests use the
  /// primary constructor with an in-memory `NativeDatabase.memory()` executor.
  AppDatabase.open() : super(driftDatabase(name: 'acsl_campaign'));

  @override
  int get schemaVersion => 1;
}
